name: Docker Image CI

on:
  push:
    branches:
    - main
    paths:
    - Dockerfile
  pull_request:
    branches:
    - main
    paths:
    - Dockerfile

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag nishipy/mkdocs:$(date +%s)
